export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCES";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCES";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

export const REFRESH_SUCCESS = "REFRESH_SUCCES";
export const REFRESH_FAIL = "REFRESH_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const RESET_USER_REGISTER_SUCCESS = "RESET_USER_REGISTER_SUCCESS";

export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";
