# Generated by Django 3.2.9 on 2021-11-12 17:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient6',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='ingredient', max_length=200, null=True), null=True, size=8),
        ),
    ]
