# Generated by Django 3.2.9 on 2021-11-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211113_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
