# Generated by Django 3.2.9 on 2021-11-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20211113_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='product_ingredient', to='base.Ingredient'),
        ),
    ]
