# Generated by Django 3.2.9 on 2021-11-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='createdAt',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='for_product', to='base.product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='base.Category'),
        ),
    ]
