# Generated by Django 3.2.9 on 2021-11-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardNavbarItem',
        ),
    ]
